#!/bin/sh

###############################################################################
# Copyright (c) 2014 IBH SYSTEMS GmbH and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBH SYSTEMS GmbH - initial API and implementation
###############################################################################

test ! -z [ "$JAVA_HOME" ] && JAVA="$JAVA_HOME/bin/java"
test ! -z [ "$JRE_HOME" ] && JAVA="$JRE_HOME/bin/java"

test -z "$JAVA" && JAVA="`which java`"

test -x "$JAVA" || ( echo "Unable to find java executable" ; exit 1 )

DIR="`dirname \"$0\"`"

"$JAVA" -jar "`ls \"$DIR\"/plugins/org.eclipse.equinox.launcher_*.jar`"