#!/bin/bash

###############################################################################
# Copyright (c) 2014 IBH SYSTEMS GmbH and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBH SYSTEMS GmbH - initial API and implementation
###############################################################################

[ ! -z "$JAVA_HOME" ] && JAVA="$JAVA_HOME/bin/java"
[ ! -z  "$JRE_HOME" ] && JAVA="$JRE_HOME/bin/java"

[ -z "$JAVA" ] && JAVA="`which java`"

[ -x "$JAVA" ] || ( echo "Unable to find java executable" ; exit 1 )

if [ -L $0 ] ; then
	DIR="$(dirname "$(readlink -f "$0")")"
else
	DIR="$(dirname "$0")"
fi

"$JAVA" -jar "$(ls "$DIR"//plugins/org.eclipse.equinox.launcher_*.jar)"