#!/bin/sh
# postinst script

set -e

case "$1" in
    configure)
$$postinst.restart$$
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

$$postinst.scripts$$

exit 0
