#!/bin/sh

USER=neoscada

set -e

# if the log directory exists, change the group and permissions
if [ -d "/var/log/$USER" ]; then
	chgrp "$USER" "/var/log/$USER"
	chmod 0770 "/var/log/$USER"
fi

if [ -d "/var/run/$USER" ]; then
	chgrp "$USER" "/var/run/$USER"
	chmod 0775 "/var/run/$USER"
fi

#DEBHELPER#

exit 0
