<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="infrastructure" nsURI="http://eclipse.org/SCADA/Configuration/Infrastructure"
    nsPrefix="infrastructure">
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Life, the universe and everything."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="1"
        eType="#//Options" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultSecurityConfiguration"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.scada.configuration.security/model/sec.ecore#//Configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMasterHandlerPriorities"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//MasterHandlerPriorities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCredentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMasterCustomizationProfile"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/profile/Profile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValueArchiveCustomizationProfile"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/profile/Profile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultDriverPassword"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//PasswordCredentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationConfigurations"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/IndependentConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultDriverAccessCredentials"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" eType="#//Configurations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//NamedDocumentable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A base interface for nodes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true" eOpposite="#//Device/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterServer" eSuperTypes="#//EquinoxApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authoratives" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.globalization/model/globalize.ecore#//Authorative"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importMaster" upperBound="-1"
        eType="#//MasterImport" containment="true" eOpposite="#//MasterImport/master">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A master import definition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" upperBound="-1"
        eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archiveTo" eType="#//ValueArchiveServer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedMaster" eType="#//MasterServer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The master server that is imported"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="master" lowerBound="1"
        eType="#//MasterServer" eOpposite="#//MasterServer/importMaster"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Some basic world options."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseDaNgpPort" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" defaultValueLiteral="2100">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The base port number for DA connections. Will be incremented by the instance number of an Equinox application."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseAeNgpPort" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" defaultValueLiteral="2200">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The base port number for AE connections. Will be incremented by the instance number of an Equinox application."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseCaNgpPort" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" defaultValueLiteral="2400">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The base port number for CA connections. Will be incremented by the instance number of an Equinox application."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseHdNgpPort" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" defaultValueLiteral="2300">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The base port number for HD connections. Will be incremented by the instance number of an Equinox application."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorPools" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/MonitorPool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPools" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/EventPool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultUserService" eType="#//UserService"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquinoxApplication" abstract="true"
      eSuperTypes="#//EquinoxBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localCredentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommonDriver" eSuperTypes="#//AbstractFactoryDriver">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A driver definition which creates a driver instance by using driver factories and a type id."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="password" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//PasswordCredentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalNode" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An unmanaged node."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemNode" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A node managed by the system."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//deployment/DeploymentMechanism"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers" upperBound="-1"
        eType="#//Driver" containment="true" eOpposite="#//Driver/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="masters" upperBound="-1"
        eType="#//MasterServer" volatile="true" transient="true" derived="true" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#applications"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueArchives" upperBound="-1"
        eType="#//ValueArchiveServer" volatile="true" transient="true" derived="true"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#applications"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applications" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Service"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueSlaves" upperBound="-1"
        eType="#//ValueArchiveSlave" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemPropertyUserService" eSuperTypes="#//UserService">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This service should only be used for testing purposes!"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//UserEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserService" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="JdbcUserService" eSuperTypes="#//UserService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/JdbcUserService"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueArchiveServer" eSuperTypes="#//EquinoxApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultArchiveconfiguration"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/ArchiveConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFactoryDriver" abstract="true"
      eSuperTypes="#//Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverTypeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//NamedDocumentable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node" eOpposite="#//Node/devices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquinoxDriver" eSuperTypes="#//AbstractFactoryDriver #//EquinoxBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessCredentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDriver" eSuperTypes="#//Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessCredentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines wether the external driver instance will block the port by binding as a service."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Driver" abstract="true" eSuperTypes="#//NamedApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//SystemNode"
        eOpposite="#//SystemNode/drivers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolTypeTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ngp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDriverPlaceholder" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Driver">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Endpoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationConfiguration" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//NamedDocumentable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This object describes application modules that extend the application that references to this element. For example a master server can reference to an application configuration element which defines an HTTP server and REST interface. So these modules will become part of the application. But it is only necessary to define these modules once, and then re-use them with multiple master servers."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/IndependentConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configurations">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A place where to store configurations and settings in the world model.&#xA;&#xA;It is also possible to store these object instances outside of the main world model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//ApplicationConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Settings"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HttpServiceModule" eSuperTypes="#//EquinoxModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        defaultValueLiteral="8080"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestExporterModule" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueArchiveSlave" eSuperTypes="#//EquinoxApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storagePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="/var/lib/neoscada/hds.slave"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageLayout" lowerBound="1"
        eType="#//SlaveStorageLayout" defaultValueLiteral="MULTI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SlaveStorageLayout">
    <eLiterals name="SINGLE"/>
    <eLiterals name="MULTI" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebAdminConsole" eSuperTypes="#//EquinoxModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="httpService" lowerBound="1"
        eType="#//HttpServiceModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OracleVMSettings" eSuperTypes="#//JavaModule">
    <eAnnotations source="http://eclipse.org/SCADA/Configuration/World/ExclusiveGroup">
      <details key="groupId" value="oracle.vm.settings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialHeapSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumHeapSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericVMSettings" eSuperTypes="#//JavaModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEquinoxDriver" abstract="true"
      eSuperTypes="#//Driver #//EquinoxBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessCredentials" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Credentials"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquinoxBase" abstract="true" interface="true"
      eSuperTypes="#//NamedApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userService" eType="#//UserService"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityConfiguration"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.security/model/sec.ecore#//Configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//ApplicationConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/IndependentConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCommonDriver" abstract="true"
      eSuperTypes="#//Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="password" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//PasswordCredentials"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventInjectorHttp" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="httpService" lowerBound="1"
        eType="#//HttpServiceModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventInjectorSyslog" eSuperTypes="#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is an event injector module for the RELP syslog protocol."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="20514"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JMXSettings" eSuperTypes="#//JavaModule">
    <eAnnotations source="http://eclipse.org/SCADA/Configuration/World/ExclusiveGroup">
      <details key="groupId" value="jmx.settings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The specific port number to use. If this is empty then the instance port number will be tried next."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instancePortOffset" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An offset which will be applied to the instance number and used as port. If it is empty and the specific port number is also not set then the JMX port will not be set."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localOnly" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticated" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssl" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignNodeHostname" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedApplication" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationAdminFileBackend" eSuperTypes="#//EquinoxModule">
    <eAnnotations source="http://eclipse.org/SCADA/Configuration/World/ExclusiveGroup">
      <details key="scada.ca.backend" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="${user.home}/.eclipse.scada/ca.#{name}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquinoxModule" abstract="true" interface="true"
      eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaModule" abstract="true" interface="true"
      eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSFileBackend" eSuperTypes="#//EquinoxModule">
    <eAnnotations source="http://eclipse.org/SCADA/Configuration/World/ExclusiveGroup">
      <details key="scada.ds.backend" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="${user.home}/.eclipse.scada/ds.#{name}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationAdminSettings" eSuperTypes="#//EquinoxModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="automaticMerge" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set to &quot;true&quot; if configurations should be merged automatically into the running system."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="settleTimeout" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//ELongObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of milliseconds to wait until changes have been settled."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
