<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modbus" nsURI="http://eclipse.org/SCADA/Configuration/Modbus"
    nsPrefix="modbus">
  <eClassifiers xsi:type="ecore:EClass" name="ModbusDevice" eSuperTypes="../../org.eclipse.scada.configuration.infrastructure/model/infrastructure.ecore#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolType" lowerBound="1"
        eType="#//ProtocolType" defaultValueLiteral="TCP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interFrameDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slaves" upperBound="-1"
        eType="#//ModbusSlave" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeSystem" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.memory/model/memory.ecore#//TypeSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusDriver" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Driver ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/EquinoxApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="masters" upperBound="-1"
        eType="#//ModbusMaster" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusSlave">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//ModbusBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitAddress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Byte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataOrder" lowerBound="1"
        eType="#//ByteOrder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProtocolType">
    <eLiterals name="TCP" literal="TCP"/>
    <eLiterals name="RTU" value="1" literal="RTU"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusMaster">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slaves" upperBound="-1"
        eType="#//ModbusSlave" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Endpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolType" lowerBound="1"
        eType="#//ProtocolType" defaultValueLiteral="TCP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interFrameDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockType" lowerBound="1"
        eType="#//RequestType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAddress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The start register."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of registers to read."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../org.eclipse.scada.configuration.memory/model/memory.ecore#//TypeDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RequestType" instanceClassName="org.eclipse.scada.da.server.osgi.modbus.RequestType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusExporter" eSuperTypes="../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/ApplicationModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//ModbusExporterDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusExporterDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ModbusExporterItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//Endpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/PropertyEntry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataOrder" lowerBound="1"
        eType="#//ByteOrder" defaultValueLiteral="BIG_ENDIAN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusExporterItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/Item"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModbusDataType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusDataType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusDouble" eSuperTypes="#//ModbusDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusSInt16" eSuperTypes="#//ModbusDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusSInt32" eSuperTypes="#//ModbusDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusUInt16" eSuperTypes="#//ModbusDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusUInt32" eSuperTypes="#//ModbusDataType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ByteOrder">
    <eLiterals name="BIG_ENDIAN"/>
    <eLiterals name="LITTLE_ENDIAN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusExporterModule" eSuperTypes="../../org.eclipse.scada.configuration.infrastructure/model/infrastructure.ecore#//Settings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataOrder" lowerBound="1"
        eType="#//ByteOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.world/model/configuration.ecore#//osgi/PropertyEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModbusExporterInterceptor" eSuperTypes="../../org.eclipse.scada.configuration.component/model/component.ecore#//ItemInterceptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" lowerBound="1"
        eType="#//ModbusExporterModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.scada.configuration.script/model/script.ecore#//Script"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
