pipeline {
	agent any
	
	environment {
	    CI = 'JENKINS'
	}


	tools {
		maven 'apache-maven-latest'
	}
	
	stages {
		stage('Build') {
			steps {
				dir ('releng/org.eclipse.neoscada.releng.p2.to.maven') {
					sh 'rm -rf ~/.m2/repository/org/eclipse/neoscada/org.eclipse.neoscada.releng.p2.to.maven*'
					sh 'MAVEN_OPTS="-Xms1024m -Xmx3072m" mvn -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true clean install'
				}
			}
		}
		stage('Archive') {
			steps {
				dir ('releng/org.eclipse.neoscada.releng.p2.to.maven') {
					archive '**/*-product/target/final/*.zip'
				}
			}
		}
		stage('Deploy') {
			steps {
				dir ('releng/org.eclipse.neoscada.releng.p2.to.maven') {
					sh 'cp org.eclipse.neoscada.releng.p2.to.maven.app-product/target/final/p2tom2-*.zip /home/data/httpd/download.eclipse.org/eclipsescada/releng/'
				}
			}
		}
	}
}