/**
 * Copyright (c) 2014 IBH SYSTEMS GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBH SYSTEMS GmbH - initial API and implementation and/or initial documentation
 *
 */
package org.eclipse.scada.configuration.iec60870.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.scada.configuration.component.ComponentPackage;
import org.eclipse.scada.configuration.component.Container;
import org.eclipse.scada.configuration.component.util.ComponentSwitch;
import org.eclipse.scada.configuration.iec60870.IEC60870Factory;
import org.eclipse.scada.configuration.iec60870.IEC60870Package;
import org.eclipse.scada.configuration.iec60870.util.IEC60870AdapterFactory;
import org.eclipse.scada.configuration.world.osgi.EquinoxApplication;
import org.eclipse.scada.configuration.world.osgi.OsgiPackage;
import org.eclipse.scada.configuration.world.osgi.util.OsgiSwitch;
import org.eclipse.ui.views.properties.IPropertySource;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into
 * calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IEC60870ItemProviderAdapterFactory extends IEC60870AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender
{
    /**
     * This keeps track of the root adapter factory that delegates to this
     * adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement
     * {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier ();

    /**
     * This helps manage the child creation extenders.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager ( IEC60870EditPlugin.INSTANCE, IEC60870Package.eNS_URI );

    /**
     * This keeps track of all the supported types checked by
     * {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object> ();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated NOT
     */
    public IEC60870ItemProviderAdapterFactory ()
    {
        this.supportedTypes.add ( IEditingDomainItemProvider.class );
        this.supportedTypes.add ( IStructuredItemContentProvider.class );
        this.supportedTypes.add ( ITreeItemContentProvider.class );
        this.supportedTypes.add ( IItemLabelProvider.class );
        this.supportedTypes.add ( IItemPropertySource.class );
        this.supportedTypes.add ( IPropertySource.class );
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.Exporter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ExporterItemProvider exporterItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.Exporter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createExporterAdapter ()
    {
        if ( this.exporterItemProvider == null )
        {
            this.exporterItemProvider = new ExporterItemProvider ( this );
        }

        return this.exporterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.Device} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected DeviceItemProvider deviceItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.Device}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDeviceAdapter ()
    {
        if ( this.deviceItemProvider == null )
        {
            this.deviceItemProvider = new DeviceItemProvider ( this );
        }

        return this.deviceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.Item} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ItemItemProvider itemItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.Item}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createItemAdapter ()
    {
        if ( this.itemItemProvider == null )
        {
            this.itemItemProvider = new ItemItemProvider ( this );
        }

        return this.itemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.ExporterItemInterceptor}
     * instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ExporterItemInterceptorItemProvider exporterItemInterceptorItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.ExporterItemInterceptor}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createExporterItemInterceptorAdapter ()
    {
        if ( this.exporterItemInterceptorItemProvider == null )
        {
            this.exporterItemInterceptorItemProvider = new ExporterItemInterceptorItemProvider ( this );
        }

        return this.exporterItemInterceptorItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.ProtocolOptions}
     * instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected ProtocolOptionsItemProvider protocolOptionsItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.ProtocolOptions}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createProtocolOptionsAdapter ()
    {
        if ( this.protocolOptionsItemProvider == null )
        {
            this.protocolOptionsItemProvider = new ProtocolOptionsItemProvider ( this );
        }

        return this.protocolOptionsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.scada.configuration.iec60870.DataModuleOptions}
     * instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected DataModuleOptionsItemProvider dataModuleOptionsItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.eclipse.scada.configuration.iec60870.DataModuleOptions}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDataModuleOptionsAdapter ()
    {
        if ( this.dataModuleOptionsItemProvider == null )
        {
            this.dataModuleOptionsItemProvider = new DataModuleOptionsItemProvider ( this );
        }

        return this.dataModuleOptionsItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory ()
    {
        return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory ();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void setParentAdapterFactory ( final ComposedAdapterFactory parentAdapterFactory )
    {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public boolean isFactoryForType ( final Object type )
    {
        return this.supportedTypes.contains ( type ) || super.isFactoryForType ( type );
    }

    /**
     * This implementation substitutes the factory itself as the key for the
     * adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter adapt ( final Notifier notifier, final Object type )
    {
        return super.adapt ( notifier, this );
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Object adapt ( final Object object, final Object type )
    {
        if ( isFactoryForType ( type ) )
        {
            final Object adapter = super.adapt ( object, type );
            if ( ! ( type instanceof Class<?> ) || ( (Class<?>)type ).isInstance ( adapter ) )
            {
                return adapter;
            }
        }

        return null;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public List<IChildCreationExtender> getChildCreationExtenders ()
    {
        return this.childCreationExtenderManager.getChildCreationExtenders ();
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Collection<?> getNewChildDescriptors ( final Object object, final EditingDomain editingDomain )
    {
        return this.childCreationExtenderManager.getNewChildDescriptors ( object, editingDomain );
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public ResourceLocator getResourceLocator ()
    {
        return this.childCreationExtenderManager;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void addListener ( final INotifyChangedListener notifyChangedListener )
    {
        this.changeNotifier.addListener ( notifyChangedListener );
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void removeListener ( final INotifyChangedListener notifyChangedListener )
    {
        this.changeNotifier.removeListener ( notifyChangedListener );
    }

    /**
     * This delegates to {@link #changeNotifier} and to
     * {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void fireNotifyChanged ( final Notification notification )
    {
        this.changeNotifier.fireNotifyChanged ( notification );

        if ( this.parentAdapterFactory != null )
        {
            this.parentAdapterFactory.fireNotifyChanged ( notification );
        }
    }

    /**
     * This disposes all of the item providers created by this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void dispose ()
    {
        if ( this.exporterItemProvider != null )
        {
            this.exporterItemProvider.dispose ();
        }
        if ( this.deviceItemProvider != null )
        {
            this.deviceItemProvider.dispose ();
        }
        if ( this.itemItemProvider != null )
        {
            this.itemItemProvider.dispose ();
        }
        if ( this.exporterItemInterceptorItemProvider != null )
        {
            this.exporterItemInterceptorItemProvider.dispose ();
        }
        if ( this.protocolOptionsItemProvider != null )
        {
            this.protocolOptionsItemProvider.dispose ();
        }
        if ( this.dataModuleOptionsItemProvider != null )
        {
            this.dataModuleOptionsItemProvider.dispose ();
        }
    }

    /**
     * A child creation extender for the {@link ComponentPackage}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public static class ComponentChildCreationExtender implements IChildCreationExtender
    {
        /**
         * The switch for creating child descriptors specific to each extended
         * class.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        protected static class CreationSwitch extends ComponentSwitch<Object>
        {
            /**
             * The child descriptors being populated.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected List<Object> newChildDescriptors;

            /**
             * The domain in which to create the children.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected EditingDomain editingDomain;

            /**
             * Creates the a switch for populating child descriptors in the
             * given domain.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            CreationSwitch ( final List<Object> newChildDescriptors, final EditingDomain editingDomain )
            {
                this.newChildDescriptors = newChildDescriptors;
                this.editingDomain = editingDomain;
            }

            /**
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            @Override
            public Object caseContainer ( final Container object )
            {
                this.newChildDescriptors.add
                        ( createChildParameter
                        ( ComponentPackage.Literals.CONTAINER__ITEM_INTERCEPTORS,
                                IEC60870Factory.eINSTANCE.createExporterItemInterceptor () ) );

                return null;
            }

            /**
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected CommandParameter createChildParameter ( final Object feature, final Object child )
            {
                return new CommandParameter ( null, feature, child );
            }

        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        @Override
        public Collection<Object> getNewChildDescriptors ( final Object object, final EditingDomain editingDomain )
        {
            final ArrayList<Object> result = new ArrayList<Object> ();
            new CreationSwitch ( result, editingDomain ).doSwitch ( (EObject)object );
            return result;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        @Override
        public ResourceLocator getResourceLocator ()
        {
            return IEC60870EditPlugin.INSTANCE;
        }
    }

    /**
     * A child creation extender for the {@link OsgiPackage}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public static class OsgiChildCreationExtender implements IChildCreationExtender
    {
        /**
         * The switch for creating child descriptors specific to each extended
         * class.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        protected static class CreationSwitch extends OsgiSwitch<Object>
        {
            /**
             * The child descriptors being populated.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected List<Object> newChildDescriptors;

            /**
             * The domain in which to create the children.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected EditingDomain editingDomain;

            /**
             * Creates the a switch for populating child descriptors in the
             * given domain.
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            CreationSwitch ( final List<Object> newChildDescriptors, final EditingDomain editingDomain )
            {
                this.newChildDescriptors = newChildDescriptors;
                this.editingDomain = editingDomain;
            }

            /**
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            @Override
            public Object caseEquinoxApplication ( final EquinoxApplication object )
            {
                this.newChildDescriptors.add
                        ( createChildParameter
                        ( OsgiPackage.Literals.EQUINOX_APPLICATION__MODULES,
                                IEC60870Factory.eINSTANCE.createExporter () ) );

                return null;
            }

            /**
             * <!-- begin-user-doc -->
             * <!-- end-user-doc -->
             *
             * @generated
             */
            protected CommandParameter createChildParameter ( final Object feature, final Object child )
            {
                return new CommandParameter ( null, feature, child );
            }

        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        @Override
        public Collection<Object> getNewChildDescriptors ( final Object object, final EditingDomain editingDomain )
        {
            final ArrayList<Object> result = new ArrayList<Object> ();
            new CreationSwitch ( result, editingDomain ).doSwitch ( (EObject)object );
            return result;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         *
         * @generated
         */
        @Override
        public ResourceLocator getResourceLocator ()
        {
            return IEC60870EditPlugin.INSTANCE;
        }
    }

}
