#!/bin/sh
# postinst script

USER=neoscada
NEOSCADA_HOME="/var/lib/$USER"

set -e



multiuserScreen="$$multiuserScreen$$"

case "$1" in
    configure)
$$create.apps$$

	if [ ! -f $NEOSCADA_HOME/.screenrc ]; then
		test "$multiuserScreen" -eq "1" && echo "multiuser on\nacladd root" > $NEOSCADA_HOME/.screenrc
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
$$stop.apps$$
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

$$postinst.scripts$$

# start apps last
case "$1" in
	configure)
	$$start.apps$$
	;;
esac

exit 0
